# config.py
ignore_patterns = [
    '*.git',
    'ignore/*',
    '*.pyc',
    '__pycache__/*',
    '*.DS_Store',
    'venv/*',
    'code_crawler/*',
    'FullyUnifiedModel/*',
    '*.png',
    '*.jpg',
    '*.jpeg',
    '*.gif',
    'runs/benchmark_1',
    'runs/demo_1',
    'runs/run_1752954844',
    'runs/run_1752958459',
    'runs/run_1752959364',
    # AdvancedMath library files to ignore
    '../src/causal_inference/*',
    '../src/clustering/*',
    '../src/dynamical_systems/*',
    '../src/evolutionary/*',
    '../src/fractal_analysis/*',
    '../src/fractional_calculus/*',
    '../src/graph/*',
    '../src/iit/*',
    '../src/info_theory/*',
    '../src/optimization/*',
    '../src/ot/*',
    '../src/pathway_analysis/*',
    '../src/rmt/*',
    '../src/sde/*',
    '../src/semantic/*',
    '../src/soc_analysis/*',
    '../src/spatial/*',
    '../src/stochastic/*',
    '../src/symbolic/*',
    '../src/thermodynamics/*',
    '../src/time_series/*',
    '../src/calculate_descriptive_stats.py',
    '../src/linear_system_solver.py',
    '../src/numerical_integrate.py',
    '../src/numerical_ode_solver.py',
    '../src/symbolic_differentiation.py',
    # 'Cogito_Research/*',
    
]